# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from wysteria.middleware.wgrpc.wysteria import grpc_pb2 as wysteria_dot_grpc__pb2


class WysteriaGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCollection = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/CreateCollection',
        request_serializer=wysteria_dot_grpc__pb2.Collection.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
        )
    self.CreateItem = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/CreateItem',
        request_serializer=wysteria_dot_grpc__pb2.Item.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
        )
    self.CreateVersion = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/CreateVersion',
        request_serializer=wysteria_dot_grpc__pb2.Version.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.IdAndNum.FromString,
        )
    self.CreateResource = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/CreateResource',
        request_serializer=wysteria_dot_grpc__pb2.Resource.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
        )
    self.CreateLink = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/CreateLink',
        request_serializer=wysteria_dot_grpc__pb2.Link.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
        )
    self.DeleteCollection = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/DeleteCollection',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.DeleteItem = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/DeleteItem',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.DeleteVersion = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/DeleteVersion',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.DeleteResource = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/DeleteResource',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.FindCollections = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/FindCollections',
        request_serializer=wysteria_dot_grpc__pb2.QueryDescs.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Collections.FromString,
        )
    self.FindItems = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/FindItems',
        request_serializer=wysteria_dot_grpc__pb2.QueryDescs.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Items.FromString,
        )
    self.FindVersions = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/FindVersions',
        request_serializer=wysteria_dot_grpc__pb2.QueryDescs.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Versions.FromString,
        )
    self.FindResources = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/FindResources',
        request_serializer=wysteria_dot_grpc__pb2.QueryDescs.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Resources.FromString,
        )
    self.FindLinks = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/FindLinks',
        request_serializer=wysteria_dot_grpc__pb2.QueryDescs.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Links.FromString,
        )
    self.PublishedVersion = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/PublishedVersion',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Version.FromString,
        )
    self.SetPublishedVersion = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/SetPublishedVersion',
        request_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.UpdateVersionFacets = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/UpdateVersionFacets',
        request_serializer=wysteria_dot_grpc__pb2.IdAndDict.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.UpdateItemFacets = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/UpdateItemFacets',
        request_serializer=wysteria_dot_grpc__pb2.IdAndDict.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.UpdateCollectionFacets = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/UpdateCollectionFacets',
        request_serializer=wysteria_dot_grpc__pb2.IdAndDict.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.UpdateResourceFacets = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/UpdateResourceFacets',
        request_serializer=wysteria_dot_grpc__pb2.IdAndDict.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )
    self.UpdateLinkFacets = channel.unary_unary(
        '/wysteria_grpc.WysteriaGrpc/UpdateLinkFacets',
        request_serializer=wysteria_dot_grpc__pb2.IdAndDict.SerializeToString,
        response_deserializer=wysteria_dot_grpc__pb2.Text.FromString,
        )


class WysteriaGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteCollection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteItem(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteResource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindCollections(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindItems(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindVersions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindResources(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindLinks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishedVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetPublishedVersion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateVersionFacets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateItemFacets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateCollectionFacets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateResourceFacets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateLinkFacets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WysteriaGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCollection': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCollection,
          request_deserializer=wysteria_dot_grpc__pb2.Collection.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
      ),
      'CreateItem': grpc.unary_unary_rpc_method_handler(
          servicer.CreateItem,
          request_deserializer=wysteria_dot_grpc__pb2.Item.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
      ),
      'CreateVersion': grpc.unary_unary_rpc_method_handler(
          servicer.CreateVersion,
          request_deserializer=wysteria_dot_grpc__pb2.Version.FromString,
          response_serializer=wysteria_dot_grpc__pb2.IdAndNum.SerializeToString,
      ),
      'CreateResource': grpc.unary_unary_rpc_method_handler(
          servicer.CreateResource,
          request_deserializer=wysteria_dot_grpc__pb2.Resource.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
      ),
      'CreateLink': grpc.unary_unary_rpc_method_handler(
          servicer.CreateLink,
          request_deserializer=wysteria_dot_grpc__pb2.Link.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Id.SerializeToString,
      ),
      'DeleteCollection': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteCollection,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'DeleteItem': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteItem,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'DeleteVersion': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteVersion,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'DeleteResource': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteResource,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'FindCollections': grpc.unary_unary_rpc_method_handler(
          servicer.FindCollections,
          request_deserializer=wysteria_dot_grpc__pb2.QueryDescs.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Collections.SerializeToString,
      ),
      'FindItems': grpc.unary_unary_rpc_method_handler(
          servicer.FindItems,
          request_deserializer=wysteria_dot_grpc__pb2.QueryDescs.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Items.SerializeToString,
      ),
      'FindVersions': grpc.unary_unary_rpc_method_handler(
          servicer.FindVersions,
          request_deserializer=wysteria_dot_grpc__pb2.QueryDescs.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Versions.SerializeToString,
      ),
      'FindResources': grpc.unary_unary_rpc_method_handler(
          servicer.FindResources,
          request_deserializer=wysteria_dot_grpc__pb2.QueryDescs.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Resources.SerializeToString,
      ),
      'FindLinks': grpc.unary_unary_rpc_method_handler(
          servicer.FindLinks,
          request_deserializer=wysteria_dot_grpc__pb2.QueryDescs.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Links.SerializeToString,
      ),
      'PublishedVersion': grpc.unary_unary_rpc_method_handler(
          servicer.PublishedVersion,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Version.SerializeToString,
      ),
      'SetPublishedVersion': grpc.unary_unary_rpc_method_handler(
          servicer.SetPublishedVersion,
          request_deserializer=wysteria_dot_grpc__pb2.Id.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'UpdateVersionFacets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateVersionFacets,
          request_deserializer=wysteria_dot_grpc__pb2.IdAndDict.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'UpdateItemFacets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateItemFacets,
          request_deserializer=wysteria_dot_grpc__pb2.IdAndDict.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'UpdateCollectionFacets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateCollectionFacets,
          request_deserializer=wysteria_dot_grpc__pb2.IdAndDict.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'UpdateResourceFacets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateResourceFacets,
          request_deserializer=wysteria_dot_grpc__pb2.IdAndDict.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
      'UpdateLinkFacets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateLinkFacets,
          request_deserializer=wysteria_dot_grpc__pb2.IdAndDict.FromString,
          response_serializer=wysteria_dot_grpc__pb2.Text.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'wysteria_grpc.WysteriaGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
